# Настройки анализа для проекта student_platform

# Removed include to avoid dependency on flutter_lints in this workspace

analyzer:
  exclude:
    - .dart_tool/**
    - build/**
    - test/**
    - ios/**
    - android/**
    - web/**
    - linux/**
    - macos/**
    - windows/**
    - backup_unused_files/**

linter:
  rules: {}

dart_code_metrics:
  extends:
    - preset:dart/recommended
    - preset:flutter/recommended

  rules:
    - check-unused-files
    - check-unused-code
    - check-unused-l10n
    - prefer-trailing-comma
    - prefer-const-border-radius
    - avoid-late-keyword
    - no-equal-then-else
    - prefer-const-constructors
    - prefer-const-literals-to-create-immutables
