name: student_platform
description: MVP в стиле Cloudmate (Flutter)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Навигация / сеть / состояния
  go_router: ^14.2.0
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Хранилище/настройки
  get_storage: ^2.1.1
  shared_preferences: ^2.3.2

  # Медиа/файлы
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  path_provider: ^2.1.4
  open_filex: ^4.4.0

  # UI / ассеты
  lottie: ^3.1.2
  cached_network_image: ^3.4.1

  # Ссылки/утилиты
  url_launcher: ^6.3.0
  emoji_picker_flutter: ^4.3.0
  intl: ^0.20.0

  # === Supabase авторизация ===
  supabase_flutter: ^2.6.0
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/fonts/
    - assets/lottie/cat_sleeping.json

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Allison
      fonts:
        - asset: assets/fonts/Allison-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript.ttf
