-- Persist per-user read state for home dashboard notifications.
--
-- This table stores only stable notification identifiers and read timestamps.
-- The notification text stays generated by the Flutter home dashboard.

create extension if not exists pgcrypto;

create table if not exists public.home_notification_reads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  notification_id text not null,
  read_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint home_notification_reads_user_notification_unique
    unique (user_id, notification_id),
  constraint home_notification_reads_notification_id_check
    check (length(trim(notification_id)) between 1 and 160)
);

create index if not exists home_notification_reads_user_id_idx
on public.home_notification_reads(user_id);

alter table public.home_notification_reads enable row level security;

create policy "home_notification_reads_read_own"
on public.home_notification_reads
for select
to authenticated
using (user_id = auth.uid());

create policy "home_notification_reads_insert_own"
on public.home_notification_reads
for insert
to authenticated
with check (user_id = auth.uid());

create policy "home_notification_reads_update_own"
on public.home_notification_reads
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

comment on table public.home_notification_reads is
  'Per-user read markers for locally generated home dashboard notifications.';

comment on column public.home_notification_reads.notification_id is
  'Stable Flutter-generated notification id, for example schedule_* or assignments_*.';
